# Use official Node.js image as base
FROM node:16-alpine

# Set working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code to the working directory
COPY . .

# Build the Vite React app
RUN npm run build

# Expose port 3001 to the outside world
EXPOSE 3001

# Command to run the React app
CMD ["npm", "run", "dev"]